### ISSUE TITLE
Add Flemish and Wallonian river basins

### ISSUE THREAD

**Issue by damianooldoni** [riparias/early-alert-webapp#10]
- [x] Flemish river basins
- [x] Walllonian river basins

Aside the three LIFE RIPARIAS river basins, we would like to add all river basins of Wallonia and Flanders. To not wait too long to do this, but I would maybe do it after #8. Still waiting for such polygons.

**Comment by damianooldoni** [comment]
River basins for Flanders can be found on: https://www.vlaanderen.be/datavindplaats/catalogus/geografische-indeling-van-watersystemen-28-04-2023
Download of shapefiles from website is possible. See attachment in this comment.
[Watersystemen_20230428_GewVLA_Shapefile.zip](https://github.com/riparias/early-alert-webapp/files/12761759/Watersystemen_20230428_GewVLA_Shapefile.zip)

**Comment by damianooldoni** [comment]
Import specifications:
- What to import: first layer called `Wsbekken`. 
- Name of the areas: values in field `BEKNAAM`
- Tags for all the polygons: `Flanders`, `river basin`. 
- Specific tags: value in field `STRMGEB`, i.e. one of `Ijzer`, `Brugse Polders`, `Schelde`.

**Comment by niconoe** [comment]
Done, data imported on the dev and prod websites!

**Comment by damianooldoni** [comment]
Nice job, @niconoe! Still, I have to reopen the issue as we are still waiting the river basins of Wallonia.

**Comment by damianooldoni** [comment]
I got an email long time ago (April) but then completely forgot. Deeply sorry. I attach the zip file with Wallonia  river basins as I got by mail.
[DGO3.Cont_riv_Perim_Action.zip](https://github.com/riparias/early-alert-webapp/files/13068003/DGO3.Cont_riv_Perim_Action.zip)

**Comment by damianooldoni** [comment]
I checked the shapefile. I modified it just a little to remove a very small river basin which is not managed and has the very same name of another one. And another one, also not managed, has a name but I had to improve it.

[river_basins_wallonia.txt](https://github.com/riparias/early-alert-webapp/files/13120567/river_basins_wallonia.txt) contains the Wallonian river basins to upload as geopackage. **IMPORTANT**: GitHub issues doesn't support **`gpkg`** file type. So, I changed the extension to **`txt`**. To be reverted locally.

**Tags** to use: `river basin` and `Wallonia`.
 
The changes are reproducible via this R code:

```r
library(sf)
library(dplyr)
library(stringr)

wall_rivers <- st_read("./DGO3.Cont_riv_Perim_Action/")
wall_rivers <- wall_rivers %>%
  dplyr::filter(.data$GESTION != "Meuse Aval") %>%
  dplyr::mutate(river_basin = dplyr::if_else(
    is.na(.data$CRNAME),
    .data$GESTION,
    .data$CRNAME)) %>%
  dplyr::mutate(river_basin = stringr::str_remove(
    .data$river_basin,
    pattern = "DIstrict du ")) %>%
  dplyr::select(OBJECTID,
                river_basin,
                geometry)
sf::st_write(obj = wall_rivers, dsn = "river_basins_wallonia.gpkg", append = FALSE)
```

**Comment by niconoe** [comment]
This has been deployed, can you check?

**Comment by damianooldoni** [comment]
Checked. Nice work 💪
