### ISSUE TITLE
Add municipalities to areas 

### ISSUE THREAD

**Issue by damianooldoni** [riparias/early-alert-webapp#18]
Requested by participants of the workshop "Digitalization and mobilization" given by @timadriaens and me during the ExotenNet event.

**Comment by damianooldoni** [comment]
Municipalities can be downloaded as geopackage from https://www.geo.be/catalog/details/1cd00540-b0ca-11ec-a863-186571a04de2?l=nl

**Comment by damianooldoni** [comment]
I have just had a look. The layer we are interested to is called `municipality`. Notice that the polygons have the Z dimension. I had to remove it for visualizing the polygon via leaflet.

## Name of the areas

The following mapping should be used as the name should be sometimes be in Dutch, sometimes in French, sometimes in German, depending on the value of the `languagestatute` column.

`languagestatute` | column to use
--- | ---
1 | `namedut`
2 | `namefre`
4 | `namedut` - `namefre`, e.g. Auderghem - Ouderghem
5 | `namedut`
6 | `namefre`
7 | `namefre`
8 | `nameger`

Notice that:
- 4 is for municipality of the Brussels capital region
- 5 6 and 7 are for municipalities with facilities for the language minorities. 5 is given to some of the Flemish municipalities on the border with Wallonia. 6 is the opposite, some Wallonian municipalities on the border with Flanders. 7 for Wallonian municipalities on the border with the German speaking community.
- 8 is the German speaking community which is fully in Wallonia.

## Tags

- All (multi)polygons must have tag `municipality`.

- The **region** they belong to (one of `Wallonia`, `Brussels` or `Flanders`) should be a tag as well. Unfortunately it is not explicitly mentioned. However, we can get the region the municipality belongs to by using the `languagestatute` column with the following mapping:

languagestatute | region (tag)
--- | ---
1 | `Flanders`
2 | `Wallonia`
4 | `Brussels`
5 | `Flanders`
6 | `Wallonia`
7 | `Wallonia`
8 | `Wallonia`

I would no add the provinces as tags: if the user wants all municipalities in one or more provinces, he/she can just select the provinces, which are already provided as areas with tag `province`.

**Comment by niconoe** [comment]
That's now implemented (soon to de deployed!)

**Comment by damianooldoni** [comment]
Many thanks @niconoe. Please, ping me when it's deployed so that I give a look at it and then I can close the issue.

**Comment by niconoe** [comment]
@damianooldoni: it's finally deployed. Sorry for the delay, I ran into weird issues due to an old GDAL version on the production server.

**Comment by damianooldoni** [comment]
No worries. Glad that the GDAL issues were solved.

Good job! Municipalities are correctly visualized and tagged.
