### ISSUE TITLE
Update text and link in right part of footnote

### ISSUE THREAD

**Issue by damianooldoni** [riparias/early-alert-webapp#5]
At the moment, the text on the right part of the footnote of the LIFE RIPARIAS alert tool contains this sentence:

> Source code version: [d826360](https://github.com/riparias/early-alert-webapp/tree/d826360)

And the link is broken.

As this text is automatically created, a change (in configuration? or in [gbif-alert](https://github.com/riparias/gbif-alert) repo?) is needed to get:

> This site is powered by [GBIF Alert](https://github.com/riparias/gbif-alert) version [4a7b8c3](https://github.com/riparias/gbif-alert/tree/4a7b8c3)

**Comment by niconoe** [comment]
This is hardcoded, and still appears because an old version is deployed in production.

After deploying the latest release, this should be fixed automatically.

**Comment by niconoe** [comment]
Application updated (v1.2.0), problem solved!
