### ISSUE TITLE
Add DVW areas

### ISSUE THREAD

**Issue by damianooldoni** [riparias/early-alert-webapp#8]
Based on useful discussion with @fjasteen, we have a better overview now about the shared areas to add for De Vlaamse Waterweg (DVW).

areas | tags
--- | ---
districts | `DVW`, `district`, one of: `aZS`, `aBS`, `DS` (departements, afdelingen)
sectors | `DVW`, `sector`, one of: `aZS`, `aBS`, `DS`, one of: `core`, `extended`
parcels within a sector | `DVW`, `parcel`, one of: `aZS`, `aBS`, `DS` (departement, afdelingen), one of: `core`, `extended` 

Some details: 
1. parcels are grouped per sector. So, we have a one-to-one replationship between parcels and sectors. If a user wants to have its own parcel, he/she will add it as a custom area.
2. almost all sectors with tag `core` have their sector counterparts with tag `extended`. Notice that these sectors share the same name. The use of tags `kern`/`extended` will guide the user to choose the right sector while maintaining the sector name short (no need to add "core" or "extended" in the sector name as prefix or suffix )

@fjasteen will send us:
1. shapefile with **districts**
2. shapefile with **sectors** defined as above. The shapefiles we have now are slightly different as the extended sectors are areas without core. They are complementary to the core sectors. We found such sectors not useful from a user point of view. The extended sectors Frédérique will send us soon will **contain** their core counterparts.
3. shapefiles with parcels per sector. See details in point 1 above. At the moment, we have an example of the parcels but they are not aggregated at sector level.

**Comment by fjasteen** [comment]
All DVW_geodata files are within this [Google Drive folder ](https://drive.google.com/drive/folders/1VHb3b39O7ouC0tRc7VEAeyGeOcb441is?usp=sharing).
1. Districts: the shapefile containing the districts polygons
2. Sector_core: the 'Kern'-areas within each sector
3. Sector_extended: the whole of the area of the sector, the 'kern'- or core- areas included
4. Sector_parcels: for each sector a multipolygon of all of the contained parcels

**Comment by damianooldoni** [comment]
Thanks @fjasteen for the shapefiles provided in the link above: very well done 👍 
@niconoe: here below a practical table of what to import and which labels to assign:

## Districts

The districts are contained in the shapefile in folder `Districts`. It's a one layer file containing 17 multipolygons.

area name | tags
-- | --
values in column `DSTRCT` | `DVW`, `district`, value in column `AFD`, i.e. one of: `aZS`, `aBS`, `DS`

## Sectors 

We have two directories containing core sectors and extended sectors

### Core sectors

The core sectors are contained in the shapefile in folder `Sector_core`. It's a one layer file containing 48 multipolygons.

area name | tags
-- | --
values in column `SCTR` | `DVW`, `sector`, `core` (also contained in column `TYPE`), value in column `AFD`, i.e. one of: `aZS`, `aBS`, `DS`

### Extended sectors

The extended sectors are contained in the shapefile in folder `Sector_extended`. It's a one layer file containing 48 multipolygons.

area name | tags
-- | --
values in column `SCTR` | `DVW`, `sector`, `extended` (also contained in column `TYPE`), value in column `AFD`, i.e. one of: `aZS`, `aBS`, `DS`

### Sector parcels

The sector parcels are contained in the shapefile in folder `Sector_parcels`. It's a one layer file containing 33 multipolygons.

area name | tags
-- | --
values in column `SCTR` | `DVW`, `parcel` (column `TYPE` = `"parcels"`, but singular is preferrable), value in column `AFD`, i.e. one of: `aZS`, `aBS`, `DS`

**Comment by niconoe** [comment]
Thanks @damianooldoni.

The areas have been imported to [dev](https://dev-alert.riparias.be/), can you have a look?

**Comment by damianooldoni** [comment]
Hi  @niconoe: it looks nice. Thanks!

Only one thing: when selecting tag `aBS` I get also all areas with tag `DS` or `AZS`. These tags are department related and therefore should be mutually exclusive: `ONE OF` rule.

**Comment by niconoe** [comment]
Indeed, that's a distraction bug :) Fixing it now!

**Comment by niconoe** [comment]
It should be better now, can you recheck?

**Comment by damianooldoni** [comment]
Great job!

**Comment by fjasteen** [comment]
Looks very nice! Thanks a lot!
