### ISSUE TITLE
Add species for DVW

### ISSUE THREAD

**Issue by damianooldoni** [riparias/early-alert-webapp#9]
DVW/EVINBO ask to add some species to the early alert tool. This will be performed after #8 is solved. So, something to plan in October/November

Plan:

- [ ] add (Dutch) vernacular names to scientific name list (Frédérique)
- [ ] finalize metadata. Notice that metadata can be modified at later stage if needed (Frédérique)
- [ ] create new repo and map to Dwc (@damianooldoni)
- [ ] publish checklist on INBO's IPT (@LienReyserhove)
- [ ] add species to alert tool via Admin configuration panel (@damianooldoni)

Note: although the amount of species to add should be quite low, we still hope to have #3 solved in the meantime.

**Comment by fjasteen** [comment]
[priorlist_vernNames.csv](https://github.com/riparias/early-alert-webapp/files/12670275/priorlist_vernNames.csv)

vernacular names are added to a column vernacular_names

**Comment by damianooldoni** [comment]
Thanks @fjasteen for the file. I will add you to LIFE RIPARIAS community as well.
